name: 'Auto Release Milestone'
description: 'Drafts a GitHub release ased on a newly closed milestone'
author: 'pqab'
outputs:
  release-url:
    description: 'The URL of the GitHub release that was drafted'
runs:
  using: 'docker'
  image: 'Dockerfile'