name: 'Auto Release Milestone'
description: 'Drafts a GitHub release ased on a newly closed milestone'
author: 'pqab'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN used to authenticate to the repository'
    required: true
outputs:
  release-url:
    description: 'The URL of the GitHub release that was drafted'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-token }}